# Contient les instructions pour lancer la configuration docker pour la webapp.

version: "3"

services:
    proxy:
        build: "nginx-pinfo2"
        image: "nginx-pinfo2"
        volumes:
            - "webapp-data:/usr/share/nginx/html/"
        ports:
            - "873:80"
        depends_on:
            - "appserver"
        restart: always
        networks:
            - masterproxy
            - default

    appserver:

        build: "wildfly-pinfo2"
        image: "wildfly-pinfo2"
        volumes:
            - "wildfly-data:/opt/jboss/wildfly/standalone/deployments"
        ports:
            - "8080:8080"
        depends_on:
            - "database"
        restart: always
        networks:
            - default
            - masterproxy

    database:
        build: "mariadb-pinfo2"
        image: "mariadb-pinfo2"
        volumes:
            - "mysql-data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "admin"
            MYSQL_DATABASE: "meskyne"
        expose:
            - "3306"
        restart: always
        networks:
            - default

volumes:
    mysql-data:
    webapp-data:
    wildfly-data:

networks:
    masterproxy:
        external: true
