#!/usr/bin/env mysql --password=admin
CREATE OR REPLACE TABLE RegularUser
(
	ID INT PRIMARY KEY NOT NULL,
	FIRST_NAME VARCHAR(25) NOT NULL,
	LAST_NAME VARCHAR(25) NOT NULL,
	USERNAME VARCHAR(25) NOT NULL,
	PASSWORD VARCHAR(25) NOT NULL,
	TOKEN LONG NOT NULL,
	ROLE ENUM('USER', 'MANAGER', 'SYSTEM_ADMIN')
)
